name: Build Blog & Push to S3

on:
  push:
    branches: [main]

jobs:
  jekyll:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    # Uses GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Build website with jekyll
    - uses:  lemonarc/jekyll-action@1.0.0

    # Set up environment variables for aws
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    # sync website to s3 bucket, relies on crednetials above.
    - name: Sync jekyll output to S3 bucket
      env:
        DISTRIBUTION_ID: ${{ secrets.AMRIK_DE_CLOUDFRONT_DISTRIBUTION_ID }}
      run: |
        aws s3 sync ./_site/ s3://amrik.de --delete
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
